apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: recipes
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/torbencarstens/recipes:{{TAG}}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
