name: Build/Publish docker image

on:
  push:
    branches:
      - master

jobs:
  build:
    name: "Build bundle.js"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.83.1'
      - name: Build
        run: hugo --minify
      - uses: actions/upload-artifact@v2
        with:
          name: publicdir
          path: public/
  build_push_docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/download-artifact@v1
        with:
          name: publicdir
      - run: |
          rm -rf public
          mv publicdir public
      - name: Build the tagged Docker image
        run: docker build -t ghcr.io/torbencarstens/recipes:${GITHUB_SHA} .
      - name: Push the tagged Docker image
        run: docker push ghcr.io/torbencarstens/recipes:${GITHUB_SHA}
  deploy:
    name: "Publish to k8s"
    runs-on: ubuntu-latest
    needs: build_push_docker
    steps:
      - uses: actions/checkout@v1
      - name: update tag in manifest.yml
        run: sed -i -e "s#{{TAG}}#$(echo ${GITHUB_SHA})#g" .kubernetes/manifest.yaml
      - uses: danielr1996/kubectl-action@1.0.0
        name: apply config
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
          args: apply -f .kubernetes/manifest.yaml
